"use client";

import { zodResolver } from "@hookform/resolvers/zod";
import { useForm } from "react-hook-form";
import { z } from "zod";
import { ArrowRight, BarChart3, Eye, EyeOff, LockKeyhole, Mail, ShieldCheck, Truck } from "lucide-react";
import { useState } from "react";
import { useRouter } from "next/navigation";
import { Button } from "@/components/ui/button";

const schema = z.object({ email: z.email("Informe um e-mail válido."), password: z.string().min(6, "A senha deve ter ao menos 6 caracteres."), remember: z.boolean() });
type FormValues = z.infer<typeof schema>;

export default function LoginPage() {
  const [show, setShow] = useState(false);
  const router = useRouter();
  const { register, handleSubmit, formState: { errors, isSubmitting } } = useForm<FormValues>({ resolver: zodResolver(schema), defaultValues: { email: "allan@empresa.com.br", password: "logisight", remember: true } });
  return <main className="grid min-h-screen bg-[#090a0c] lg:grid-cols-[1.08fr_.92fr]">
    <section className="relative hidden overflow-hidden border-r border-white/[.07] p-12 lg:flex lg:flex-col lg:justify-between">
      <div className="absolute inset-0 bg-[radial-gradient(circle_at_20%_15%,rgba(37,99,235,.22),transparent_35%),radial-gradient(circle_at_70%_75%,rgba(15,61,145,.16),transparent_38%)]"/>
      <div className="relative z-10 flex items-center gap-3"><div className="grid size-11 place-items-center rounded-2xl bg-gradient-to-br from-blue-500 to-blue-800 shadow-[0_14px_40px_rgba(37,99,235,.3)]"><Truck size={21}/></div><div><p className="text-lg font-bold">Logi<span className="text-blue-400">Sight</span></p><p className="text-[9px] uppercase tracking-[.2em] text-zinc-600">Intelligence</p></div></div>
      <div className="relative z-10 max-w-xl"><span className="inline-flex items-center gap-2 rounded-full border border-blue-500/20 bg-blue-500/10 px-3 py-1.5 text-[10px] font-semibold uppercase tracking-[.12em] text-blue-300"><BarChart3 size={13}/>Business Intelligence</span><h1 className="mt-6 text-5xl font-semibold leading-[1.08] tracking-[-.045em] text-white">Decisões logísticas com dados em que você pode confiar.</h1><p className="mt-5 max-w-lg text-sm leading-6 text-zinc-500">Transforme a planilha operacional em indicadores, auditorias e análises gerenciais — sem alterar a rotina do Allan.</p><div className="mt-10 grid grid-cols-3 gap-3">{[["1.569","pedidos"],["R$ 14,4 mi","movimentados"],["99,2%","integridade"]].map(([value,label])=><div key={label} className="rounded-xl border border-white/[.07] bg-white/[.025] p-4 backdrop-blur"><p className="text-lg font-semibold text-zinc-100">{value}</p><p className="mt-1 text-[10px] uppercase tracking-[.08em] text-zinc-600">{label}</p></div>)}</div></div>
      <p className="relative z-10 flex items-center gap-2 text-[10px] text-zinc-700"><ShieldCheck size={13}/>Acesso protegido e atividades auditadas</p>
    </section>
    <section className="flex items-center justify-center p-6 sm:p-12"><div className="w-full max-w-[400px]"><div className="mb-10 flex items-center gap-3 lg:hidden"><div className="grid size-10 place-items-center rounded-xl bg-blue-600"><Truck size={19}/></div><p className="font-bold">Logi<span className="text-blue-400">Sight</span></p></div><p className="text-[10px] font-semibold uppercase tracking-[.16em] text-blue-400">Bem-vindo de volta</p><h2 className="mt-3 text-3xl font-semibold tracking-tight text-white">Acesse sua conta</h2><p className="mt-2 text-sm text-zinc-600">Use suas credenciais corporativas para continuar.</p><form onSubmit={handleSubmit(async()=>{await new Promise(r=>setTimeout(r,350));router.push("/");})} className="mt-8 space-y-5"><label className="block"><span className="mb-2 block text-xs font-medium text-zinc-400">E-mail</span><div className="relative"><Mail className="absolute left-3 top-1/2 -translate-y-1/2 text-zinc-600" size={16}/><input {...register("email")} className="h-12 w-full rounded-xl border border-white/10 bg-[#0d0e10] pl-10 pr-3 text-sm text-white outline-none focus:border-blue-500/60 focus:ring-2 focus:ring-blue-500/10"/></div>{errors.email&&<span className="mt-1.5 block text-[11px] text-rose-400">{errors.email.message}</span>}</label><label className="block"><span className="mb-2 block text-xs font-medium text-zinc-400">Senha</span><div className="relative"><LockKeyhole className="absolute left-3 top-1/2 -translate-y-1/2 text-zinc-600" size={16}/><input type={show?"text":"password"} {...register("password")} className="h-12 w-full rounded-xl border border-white/10 bg-[#0d0e10] pl-10 pr-11 text-sm text-white outline-none focus:border-blue-500/60 focus:ring-2 focus:ring-blue-500/10"/><button type="button" aria-label={show?"Ocultar senha":"Mostrar senha"} onClick={()=>setShow(!show)} className="absolute right-3 top-1/2 -translate-y-1/2 text-zinc-600 hover:text-zinc-300">{show?<EyeOff size={16}/>:<Eye size={16}/>}</button></div>{errors.password&&<span className="mt-1.5 block text-[11px] text-rose-400">{errors.password.message}</span>}</label><div className="flex items-center justify-between"><label className="flex items-center gap-2 text-xs text-zinc-500"><input type="checkbox" {...register("remember")} className="size-4 rounded border-white/10 bg-[#0d0e10] accent-blue-600"/>Lembrar-me</label><button type="button" className="text-xs font-medium text-blue-400 hover:text-blue-300">Esqueci minha senha</button></div><Button className="h-12 w-full" disabled={isSubmitting}>{isSubmitting?"Validando acesso...":<>Entrar<ArrowRight size={16}/></>}</Button></form><p className="mt-8 text-center text-[10px] text-zinc-700">Ambiente corporativo • Acessos e ações são registrados</p></div></section>
  </main>;
}
